import zoologico

especie1=zoologico.Mizoologico("cafe",".4m","frondoso")
print ("Especie:",zoologico.Mizoologico.mylist[0],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("amarillo","1m","melenudo")
print ("Especie:",zoologico.Mizoologico.mylist[1],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("cafe","1.80m","Peludo")
print ("Especie:",zoologico.Mizoologico.mylist[2],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("gris","1.75m","sin pelo")
print ("Especie:",zoologico.Mizoologico.mylist[3],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("negro",".8m","Pelaje suave")
print ("Especie:",zoologico.Mizoologico.mylist[4],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("cafe",".7m","pelaje escaso y arido")
print ("Especie:",zoologico.Mizoologico.mylist[5],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("naranja y negro","1m","pelaje frondoso")
print ("Especie:",zoologico.Mizoologico.mylist[6],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("cafe y blanco",".4m","plumaje")
print ("Especie:",zoologico.Mizoologico.mylist[7],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("cafe","1.75m","frondoso y denso")
print ("Especie:",zoologico.Mizoologico.mylist[8],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
print("")
print("")

especie1=zoologico.Mizoologico("blanco y negro",".65m","sin pelaje")
print ("Especie:",zoologico.Mizoologico.mylist[9],)
print("Su color es:",especie1.color)
print("Su altura es de:",especie1.altura)
print("su pelaje es:",especie1.pelaje)
