print("") 
import biblioteca

print ("A continuacion los libros disponibles en la libreria")
print("") 
L1=biblioteca.Libro1("Mobie Dick","Arthur",680)
print("Libro:",L1.nombre)
print("Autor:",L1.autor)
print("Paginas:",L1.paginas)
print("") 
L2=biblioteca.Libro2("Caramelos","Paula Dalli",250)
print("Libro:",L2.nombre)
print("Autor:",L2.autor)
print("Paginas:",L2.paginas)
print("") 
L3=biblioteca.Libro3("Loca","Espositop",260)
print("Libro:",L3.nombre)
print("Autor:",L3.autor)
print("Paginas:",L3.paginas)
print("") 
L4=biblioteca.Libro4("Dirige tu vida","Pau Forner",200)
print("Libro:",L4.nombre)
print("Autor:",L4.autor)
print("Paginas:",L4.paginas)
print("") 
L5=biblioteca.Libro5("Recetas","Fra Blanco",220)
print("Libro:",L5.nombre)
print("Autor:",L5.autor)
print("Paginas:",L5.paginas)
print("") 
L6=biblioteca.Libro6("El hombre que no deberiamos ser","Octavio Salazar",300)
print("Libro:",L6.nombre)
print("Autor:",L6.autor)
print("Paginas:",L6.paginas)
print("") 
L7=biblioteca.Libro7("El legado de los espias","John le Carre",260)
print("Libro:",L7.nombre)
print("Autor:",L7.autor)
print("Paginas:",L7.paginas)
print("") 
L8=biblioteca.Libro8("La bailarina","Jesus Palacios",280)
print("Libro:",L8.nombre)
print("Autor:",L8.autor)
print("Paginas:",L8.paginas)
print("") 
L9=biblioteca.Libro9("Carmen","Fernando Cruz",560)
print("Libro:",L9.nombre)
print("Autor:",L9.autor)
print("Paginas:",L9.paginas)
print("") 
L10=biblioteca.Libro10("El perro maldito","Juan Asterisco",800)
print("Libro:",L10.nombre)
print("Autor:",L10.autor)
print("Paginas:",L10.paginas)
print("") 
