#zoologico 2 Eduardo Carracedo Sotelo
print("") 
import zoologico

print ("A continuacion los tipos de animales que hay en el zoologico.")
print("") 
#1
Animal1=zoologico.Gorila("Gorila","Cafe","Pelaje grueso y brazos grandes")
Animal1.Truco1("ladrar","Volar","Nadar","Correr")
Animal1.Truco2("comer")
Animal1.Truco3("bostezar")
print("Animal:",Animal1.nombre)
print("color:",Animal1.color)
print("Caracteristica:",Animal1.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[2],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#2
Animal2=zoologico.Leon("Leon","Amarillo","Melena grande y colmillos afilados")
print("Animal:",Animal2.nombre)
print("color:",Animal2.color)
print("Caracteristica:",Animal2.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[2],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#3
Animal3=zoologico.Oso("Oso","Cafe","Pelaje grueso y patas grandes")
print("Animal:",Animal3.nombre)
print("color:",Animal3.color)
print("Caracteristica:",Animal3.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:","\n",*Animal1.comer,"\n",*Animal1.bostezar,"\n",Animal1.mastrucos[2])
print("") 
#4
Animal4=zoologico.Hipopotamo("Hipopotamo","Gris","Cuerpo y colmillos grandes")
print("Animal:",Animal4.nombre)
print("color:",Animal4.color)
print("Caracteristica:",Animal4.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[3],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#5
Animal5=zoologico.Rana("Rana","Verde","pequeña y escurridiza")
print("Animal:",Animal5.nombre)
print("color:",Animal5.color)
print("Caracteristica:",Animal5.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[3],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#6
Animal6=zoologico.Lobo("Lobo","Cafe o gris","Pelaje grueso y patas medianas")
print("Animal:",Animal6.nombre)
print("color:",Animal6.color)
print("Caracteristica:",Animal6.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[2],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#7
Animal7=zoologico.Aguila("Aguila","Cafe","Plumaje vistoro")
print("Animal:",Animal7.nombre)
print("color:",Animal7.color)
print("Caracteristica:",Animal7.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",Animal1.mastrucos[1],"\n",*Animal1.comer,"\n",*Animal1.bostezar)
print("") 
#8
Animal8=zoologico.Cocodrilo("Cocodrilo","Verde","Piel llena de escamas")
print("Animal:",Animal8.nombre)
print("color:",Animal8.color)
print("Caracteristica:",Animal8.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",*Animal1.comer,"\n",Animal1.mastrucos[3],"\n",*Animal1.bostezar)
print("") 
#9
Animal9=zoologico.Pescado("Pescado","Varios colores","Tiene escamas y branquias")
print("Animal:",Animal9.nombre)
print("color:",Animal9.color)
print("Caracteristica:",Animal9.crc)
print("Este amiguito solo puede nadar")
print("") 
#10
Animal10=zoologico.Jirafa("Jirafa","Amarilla con manchas cafe","cuello largo y patas largas")
print("Animal:",Animal10.nombre)
print("color:",Animal10.color)
print("Caracteristica:",Animal10.crc)
print("3 acciones que el",Animal1.nombre,"puede hacer perfectamente:""\n",*Animal1.comer,"\n",*Animal1.bostezar,"\n",Animal1.mastrucos[2])