import POA

Aguila=POA.Aguila("Aguila","viva","medio","grandes","plumas")
print("Especie:",Aguila.nombre)
print("Estado:",Aguila.estado)
print("Tamaño del pico:",Aguila.pico)
print("Tamaño de las alas:",Aguila.alas)
print("Sobre la piel tiene:",Aguila.piel)
print("\n")


Halcon=POA.Halcon("Halcon","viva","pequeño","medianas","plumas")
print("Especie:",Halcon.nombre)
print("Estado:",Halcon.estado)
print("Tamaño del pico:",Halcon.pico)
print("Tamaño de las alas:",Halcon.alas)
print("Sobre la piel tiene:",Halcon.piel)
print("\n")

Canguro=POA.Canguro("Canguro","vivo","rojizo","grande","grandes")
print("Especie:",Canguro.nombre)
print("Estado:",Canguro.estado)
print("Color:",Canguro.color)
print("Tamano:",Canguro.tamano)
print("Orejas:",Canguro.orejas)
print("\n")

Oso=POA.Oso("Oso","vivo","pardo","grande","grandes")
print("Especie:",Oso.nombre)
print("Estado:",Oso.estado)
print("Color:",Oso.color)
print("Tamano:",Oso.tamano)
print("Garras",Oso.garras)
print("\n")

Lobo=POA.Lobo("Lobo","vivo","gris","grande","grandes colmillos")

print("Especie:",Lobo.nombre)
print("Estado:",Lobo.estado)
print("Color:",Lobo.color)
print("Tamano:",Lobo.tamano)
print("Dientes:",Lobo.dientes)
print("\n")

Cocodrilo=POA.cocodrilo("cocodrilo","vivo","verde","7 metros de largo","grandes dientes")

print("Especie:",Cocodrilo.nombre)
print("Estado:",Cocodrilo.estado)
print("Color:",Cocodrilo.color)
print("Tamano:",Cocodrilo.tamano)
print("Dientes:",Cocodrilo.dientes)
print("\n")

Iguana=POA.Iguana("Iguana","viva","verde claro, o grises","30 a 40 cm")
print("Especie:",Iguana.nombre)
print("Estado:",Iguana.estado)
print("Color:",Iguana.color)
print("Tamano:",Iguana.tamano)
print("Alimentacion",Iguana.alimentacion)
print("\n")

Foca=POA.Foca("Foca","viva","gris oscuro","1.7 metros")
print("Especie:",Foca.nombre)
print("Estado:",Foca.estado)
print("Color:",Foca.color)
print("Tamano:",Foca.tamano)
print("Alimentacion",Foca.alimentacion)
print("\n")
Guacamaya=POA.Guacamaya("Guacamaya","viva","verde,azul,rojas,amarillas","81cm a 91cm","pequeno","medianas")
print("Especie:",Guacamaya.nombre)
print("Estado:",Guacamaya.estado)
print("Color:",Guacamaya.color)
print("Tamano:",Guacamaya.tamano)
print("Alimentacion",Guacamaya.alimentacion)
print("Tamaño del pico:",Guacamaya.pico)
print("Tamaño de las alas",Guacamaya.alas)
print("\n")
Rana=POA.Rana("Rana","viva","verde","15 cm")
print("Especie:",Rana.nombre)
print("Estado:",Rana.estado)
print("Color:",Rana.color)
print("Tamano:",Rana.tamano)
print("Alimentacion",Rana.alimentacion)
print("\n")

