import biblioteca

Eragon= biblioteca.Ciencia_ficcion("Eragon"," Christopher Paolini","Roca Editorial","544 paginas")
print("Titulo:",Eragon.titulo)
print("Autor:",Eragon.autor)
print("Editorial:",Eragon.editorial)
print("Numero de paginas:",Eragon.nopaginas)
print("\n")
Div_Com=biblioteca.Lit_clasica("La Divina Comedia","Dante Alighieri","Oceano expres","536 pagina")
print("Titulo:",Div_Com.titulo)
print("Autor:",Div_Com.autor)
print("Editorial:",Div_Com.editorial)
print("Numero de paginas:",Div_Com.nopaginas)
print("\n")
Iliada=biblioteca.Lit_clasica("La Iliada","Homero","Porrua","500 paginas")
print("Titulo:",Iliada.titulo)
print("Autor:",Iliada.autor)
print("Editorial:",Iliada.editorial)
print("Numero de paginas:",Iliada.nopaginas)
print("\n")
Geologia=biblioteca.Geologia("Geologia.Dinamica y evolucion de la tierra","Manuel Pozo Rodriguez,Reed Wicander,James S. Monroe","Paraninfo","744 pagina")
print("Titulo:",Geologia.titulo)
print("Autor:",Geologia.autor)
print("Editorial:",Geologia.editorial)
print("Numero de paginas:",Geologia.nopaginas)
print("\n")
Mate=biblioteca.Matematicas("Algebra","Charles H. Lehmann","Limusa","464 paginas")
print("Titulo:",Mate.titulo)
print("Autor:",Mate.autor)
print("Editorial:",Mate.editorial)
print("Numero de paginas:",Mate.nopaginas)
print("\n")
fis=biblioteca.Fisica("Fisica para ingenieria y ciencias","Hans C. Ohanian,John T. Markert","Mc Graw Hill","689 paginas")
print("Titulo:",fis.titulo)
print("Autor:",fis.autor)
print("Editorial:",fis.editorial)
print("Numero de paginas:",fis.nopaginas)



