#Benjamin Cruz Sarmiento

import ZOOLOGICOBCS

#Definiendo a los libros y sus atributos
Animal1=ZOOLOGICOBCS.ZOOBCS("Gorila","Macho",190,20)
print("Nombre del animal :", Animal1.Animal)
print("El genero del animal es: ",Animal1.Genero)
print("Tamano del animal: ",Animal1.Tamano," cm.")
print("Edad de vida del animal: ",Animal1.Edaddevida,"anos")
print("")
print("")

Animal2=ZOOLOGICOBCS.ZOOBCS("Leon","Macho",160,12)
print("Nombre del animal :", Animal2.Animal)
print("El genero del animal es: ",Animal2.Genero)
print("Tamano del animal: ",Animal2.Tamano," cm.")
print("Edad de vida del animal: ",Animal2.Edaddevida,"anos")
print("")
print("")

Animal3=ZOOLOGICOBCS.ZOOBCS("Leopardo","Hembra",50,4)
print("Nombre del animal :", Animal3.Animal)
print("El genero del animal es: ",Animal3.Genero)
print("Tamano del animal: ",Animal3.Tamano," cm.")
print("Edad de vida del animal: ",Animal3.Edaddevida,"anos")
print("")
print("")

Animal4=ZOOLOGICOBCS.ZOOBCS("Tortuga","Macho",56,80)
print("Nombre del animal :", Animal4.Animal)
print("El genero del animal es: ",Animal4.Genero)
print("Tamano del animal: ",Animal4.Tamano," cm.")
print("Edad de vida del animal: ",Animal4.Edaddevida,"anos")
print("")
print("")

Animal5=ZOOLOGICOBCS.ZOOBCS("Iguana","Hembra",30,17)
print("Nombre del animal :", Animal5.Animal)
print("El genero del animal es: ",Animal5.Genero)
print("Tamano del animal: ",Animal5.Tamano," cm.")
print("Edad de vida del animal: ",Animal5.Edaddevida,"anos")
print("")
print("")

Animal6=ZOOLOGICOBCS.ZOOBCS("Perro","Macho",80,7)
print("Nombre del animal :", Animal6.Animal)
print("El genero del animal es: ",Animal6.Genero)
print("Tamano del animal: ",Animal6.Tamano," cm.")
print("Edad de vida del animal: ",Animal6.Edaddevida,"anos")
print("")
print("")

Animal7=ZOOLOGICOBCS.ZOOBCS("Aguila","Hembra",67,9)
print("Nombre del animal :", Animal7.Animal)
print("El genero del animal es: ",Animal7.Genero)
print("Tamano del animal: ",Animal7.Tamano," cm.")
print("Edad de vida del animal: ",Animal7.Edaddevida,"anos")
print("")
print("")

Animal8=ZOOLOGICOBCS.ZOOBCS("Jirafa","Macho",410,8)
print("Nombre del animal :", Animal8.Animal)
print("El genero del animal es: ",Animal8.Genero)
print("Tamano del animal: ",Animal8.Tamano," cm.")
print("Edad de vida del animal: ",Animal8.Edaddevida,"anos")
print("")
print("")

Animal9=ZOOLOGICOBCS.ZOOBCS("Elefante","Hembra",250,5)
print("Nombre del animal :", Animal9.Animal)
print("El genero del animal es: ",Animal9.Genero)
print("Tamano del animal: ",Animal9.Tamano," cm.")
print("Edad de vida del animal: ",Animal9.Edaddevida,"anos")
print("")
print("")

Animal10=ZOOLOGICOBCS.ZOOBCS("Hipopotamo","Hembra",150,4)
print("Nombre del animal :", Animal10.Animal)
print("El genero del animal es: ",Animal10.Genero)
print("Tamano del animal: ",Animal10.Tamano," cm.")
print("Edad de vida del animal: ",Animal10.Edaddevida,"anos")
print("")
print("")
