# Santes Mejia Antonio
print "...Tecnicas de programacion.."

import pedidos_SAM


lista_SAM.Pedido("Sandia")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Mandarina")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Mandarina")
lista_SAM.Pedido("Sandia")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Mandarina")
lista_SAM.Pedido("Sandia")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Platano")
ista_SAM.Pedido("Sandia")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Melon")
lista_SAM.Pedido("Platano")
lista_SAM.Pedido("Mandarina")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")
lista_SAM.Pedido("Naranja")
lista_SAM.Pedido("Guayaba")

pedidos_SAM.lista()

pedidos_SAM.Entrega()

