#Funcional en python, no python3

import pedidos_yaxkin09

pedidos_yaxkin09.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Sandia")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Uva")
pedidos_yaxkin09.Pedido("Melon")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Sandia")
pedidos_yaxkin09.Pedido("Sandia")
pedidos_yaxkin09.Pedido("Uva")
pedidos_yaxkin09.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Uva")
pedidos_yaxkin09.Pedido("Uva")
pedidos_yaxkin09.Pedido("Uva")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Melon")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Manzana")

pedidos_yaxkin09.Lista()

pedidos_yaxkin09.Entrega()

