import lista_eduardo

lista_eduardo.Pedido("Guanabana")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Frambuesa")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Melocoton")
lista_eduardo.Pedido("Durazno")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Papaya")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Frambuesa")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Melocoton")
lista_eduardo.Pedido("Durazno")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Papaya")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Ciruela")
lista_eduardo.Pedido("Guanabana")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Higo")
lista_eduardo.Pedido("Ciruela")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Higo")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Frambuesa")
lista_eduardo.Pedido("Guanabana")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Kaki")
lista_eduardo.Pedido("Melocoton")
lista_eduardo.Pedido("Durazno")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Guanabana")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Papaya")
lista_eduardo.Pedido("Uva")
lista_eduardo.Pedido("Guanabana")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Ciruela")
lista_eduardo.Pedido("Zarzamora")
lista_eduardo.Pedido("Higo")





lista_eduardo.Lista()

lista_eduardo.Entrega()
