import Pedidos

Pedidos.Pedido("Mandarina")
Pedidos.Pedido("Sandia")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Manzana")
Pedidos.Pedido("Uva")
Pedidos.Pedido("Melon")
Pedidos.Pedido("Durazno")
Pedidos.Pedido("Mango")
Pedidos.Pedido("Manzana")
Pedidos.Pedido("Durazno")
Ppedidos.Pedido("Sandia")
Pedidos.Pedido("Sandia")
Pedidos.Pedido("Uva")
Pedidos.Pedido("Mandarina")
Pedidos.Pedido("Mango")
Pedidos.Pedido("Uva")
Pedidos.Pedido("Uva")
Pedidos.Pedido("Uva")
Pedidos.Pedido("Toronja")
Pedidos.Pedido("Melon")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Manzana")
Pedidos.Pedido("Manzana")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Naranja")
Pedidos.Pedido("Durazno")
Pedidos.Pedido("Durazno")
pedidos.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Mandarina")
pedidos_yaxkin09.Pedido("Manzana")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Toronja")
pedidos_yaxkin09.Pedido("Naranja")
pedidos_yaxkin09.Pedido("Mango")
pedidos_yaxkin09.Pedido("Durazno")
pedidos_yaxkin09.Pedido("Manzana")

pedidos_yaxkin09.Lista()

pedidos_yaxkin09.Entrega().Pedido("Toronja")
Pedidos
