import listapedidoNG

listapedidoNG.Agregar("Fanta")
listapedidoNG.Agregar("Manzanita")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("Sidral")
listapedidoNG.Agregar("Mirinda")
listapedidoNG.Agregar("7Up")
listapedidoNG.Agregar("CocaCola")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("7Up")
listapedidoNG.Agregar("Manzanita")
listapedidoNG.Agregar("Fresca")
listapedidoNG.Agregar("Yoli")
listapedidoNG.Agregar("Fanta")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("CocaCola")
listapedidoNG.Agregar("Yoli")
listapedidoNG.Agregar("Fresca")
listapedidoNG.Agregar("Mirinda")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("Manzanita")
listapedidoNG.Agregar("Mirinda")
listapedidoNG.Agregar("CocaCola")
listapedidoNG.Agregar("Yoli")
listapedidoNG.Agregar("Fresca")
listapedidoNG.Agregar("Mirinda")
listapedidoNG.Agregar("CocaCola")
listapedidoNG.Agregar("Fresca")
listapedidoNG.Agregar("Fanta")
listapedidoNG.Agregar("Manzanita")
listapedidoNG.Agregar("Sidral")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("Sidral")
listapedidoNG.Agregar("CocaCola")
listapedidoNG.Agregar("Yoli")
listapedidoNG.Agregar("Fanta")
listapedidoNG.Agregar("Fresca")
listapedidoNG.Agregar("Mirinda")
listapedidoNG.Agregar("Sidral")
listapedidoNG.Agregar("Pepsi")
listapedidoNG.Agregar("CocaCola")

listapedidoNG.Entrega()

listapedidoNG.Lista()