
import Lalo_program

Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Brocoli")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Platano")
Lalo_program.Pedido("Fresa")
Lalo_program.Pedido("Melon")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Kiwi")
Lalo_program.Pedido("Mango")
Lalo_program.Pedido("Platano")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Brocoli")
Lalo_program.Pedido("Brocoli")
Lalo_program.Pedido("Fresa")
Lalo_program.Pedido("Pera")
Lalo_program.Pedido("Mango")
Lalo_program.Pedido("Fresa")
Lalo_program.Pedido("Fresa")
Lalo_program.Pedido("Fresa")
Lalo_program.Pedido("Kiwi")
Lalo_program.Pedido("Melon")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Manzana")
Lalo_program.Pedido("Manzana")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Pera")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Pera")
Lalo_program.Pedido("Platano")
Lalo_program.Pedido("Mango")
Lalo_program.Pedido("Kiwi")
Lalo_program.Pedido("Kiwi")
Lalo_program.Pedido("Naranja")
Lalo_program.Pedido("Mango")
Lalo_program.Pedido("Durazno")
Lalo_program.Pedido("Platano")

Lalo_program.Lista()

Lalo_program.Entrega()